# Site settings
title: Morning Sail
subtitle: ["Hang's Blog"]
keywords: hang
description: 技术 生活 艺术
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Whitejadehang.github.io/" # 你的域名
page_no_title: "hang's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: hang
email: zhanhang@zju.edu.cn
github_username: Whitejadehang

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
#links: # 友情链接

#  - title: ccslience's blog
#    url: http://ccslience.oukohou.wang/
#  - title: oukohou's github
#    url: https://github.com/oukohou
#  - title: Jekyll blog system
#    url: http://jekyllcn.com/


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/WhitejadeHang


valine:
  enable: true
  app_id:  CBNCHedfWqgxWjbCI1A4e8XD-gzGzoHsz
  app_key: 0KU0MbEaAR3LnVJfd5LrYOuH
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 只需要输入一个昵称就可以留言啦~
  guest_info: nick,mail
  pageSize: 10
